apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-py-msrv
spec:
  replicas: 2

  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0

  selector:
    matchLabels:
      app: devops-py-msrv

  template:
    metadata:
      labels:
        app: devops-py-msrv

    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - devops-backend
              topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - devops-py-msrv
                topologyKey: kubernetes.io/hostname
      containers:
        - name: python-msrv
          image: devops-python
          imagePullPolicy: Always

          ports:
            - name: python-port
              containerPort: 8000

          envFrom:
            - configMapRef:
                name: devops-config

          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: OPENAI_API_KEY

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: GOOGLE_API_KEY

            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: devops-secrets
                  key: HF_TOKEN

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: devops-py-service

spec:
  selector:
    app: devops-py-msrv

  ports:
    - protocol: TCP
      port: 80
      targetPort: python-port

  type: ClusterIP